import{afterEach,describe,expect,it,vi}from'vitest';import{MatomoProvider,NoneProvider}from'../src/analytics.js';import{snapshotId}from'../src/core.js';

afterEach(()=>vi.unstubAllGlobals());
const matomoConfig={profile:'umbraco',domain:'umbraco.test',gscProperty:'sc-domain:umbraco.test',ga4PropertyId:'',analyticsProvider:'matomo' as const,matomoUrl:'https://analytics.umbraco.test/',matomoSiteId:'7',matomoTokenAuth:'secret-token',dataDir:'/tmp/site-signal-umbraco',reportDir:'/tmp/site-signal-umbraco/reports',lag:3,cap:5000,analyticsCap:10000,trackingParams:[]};

describe('analytics providers',()=>{
  it('normalizes Matomo page and referrer reports without exposing the token in the URL',async()=>{const calls:any[]=[];vi.stubGlobal('fetch',vi.fn(async(url:any,init:any)=>{calls.push({url:String(url),body:String(init.body)});const params=new URLSearchParams(String(init.body));if(params.get('method')==='Actions.getPageUrls')return new Response(JSON.stringify([{label:'/docs/?utm_source=x',nb_visits:8,nb_hits:12,nb_uniq_pageviews:7,entry_nb_visits:3,bounce_rate:0.25}]));return new Response(JSON.stringify([{label:'Search Engines',nb_visits:5,nb_actions:9,nb_conversions:1}]));}));const evidence=await new MatomoProvider(matomoConfig).landingEvidence({start:'2026-01-01',end:'2026-01-28'});expect(evidence.rows).toEqual([{url:'/docs/?utm_source=x',acquisition:null,metrics:{visits:8,pageviews:12,uniquePageviews:7,entries:3,bounceRate:.25}}]);expect(evidence.sourceSummaries[0]).toMatchObject({type:'Matomo referrer type',value:'Search Engines',metrics:{visits:5}});expect(calls).toHaveLength(2);expect(calls[0].url).not.toContain('secret-token');expect(calls[0].body).toContain('token_auth=secret-token');});
  it('supports GSC-only analytics evidence',async()=>{const evidence=await new NoneProvider().landingEvidence({start:'2026-01-01',end:'2026-01-28'});expect(evidence).toMatchObject({provider:'none',rows:[],coverage:{complete:true}});});
  it('includes profile and provider in a snapshot id',()=>expect(snapshotId(matomoConfig,{start:'2026-01-01',end:'2026-01-28'})).toBe('umbraco_matomo_2026-01-01_2026-01-28'));
});
