import {google} from 'googleapis';import {config,AnalyticsEvidence,AnalyticsProviderName,Config,Period} from './core.js';import {oauth} from './google.js';

export interface AnalyticsProvider{name:AnalyticsProviderName;capabilities():string[];landingEvidence(period:Period):Promise<AnalyticsEvidence>}
const number=(value:unknown)=>Number(value||0);
const ga4Labels={sessions:'GA4 sessions',engagedSessions:'GA4 engaged sessions',engagementRate:'GA4 engagement rate'};

export class Ga4Provider implements AnalyticsProvider{name='ga4' as const;constructor(private c:Config){}capabilities(){return['landing-page acquisition by session source / medium','sessions','engaged sessions','engagement rate']}async landingEvidence(period:Period){const api=google.analyticsdata({version:'v1beta',auth:oauth(this.c).client}),r=await api.properties.runReport({property:`properties/${this.c.ga4PropertyId}`,requestBody:{dateRanges:[{startDate:period.start,endDate:period.end}],dimensions:[{name:'landingPagePlusQueryString'},{name:'sessionSourceMedium'}],metrics:[{name:'sessions'},{name:'engagedSessions'},{name:'engagementRate'}],limit:String(this.c.analyticsCap)}}),rows=(r.data.rows||[]).map(x=>({url:x.dimensionValues?.[0]?.value||'',acquisition:{type:'GA4 session source / medium',value:x.dimensionValues?.[1]?.value||'(not set)'},metrics:{sessions:number(x.metricValues?.[0]?.value),engagedSessions:number(x.metricValues?.[1]?.value),engagementRate:number(x.metricValues?.[2]?.value)}}));return{provider:this.name,metricLabels:ga4Labels,rows,sourceSummaries:[],coverage:{complete:rows.length<this.c.analyticsCap,limitations:rows.length>=this.c.analyticsCap?[`GA4 response reached the configured ${this.c.analyticsCap}-row cap.`]:[]}}}}

const matomoLabels={visits:'Matomo visits',pageviews:'Matomo pageviews',uniquePageviews:'Matomo unique pageviews',entries:'Matomo entries',bounceRate:'Matomo bounce rate'};
function matomoEndpoint(raw:string){const base=new URL(raw);if(base.protocol!=='https:')throw Error('MATOMO_URL must use HTTPS.');if(!base.pathname.endsWith('/'))base.pathname+='/';return new URL('index.php',base).toString()}
async function matomoRequest(c:Config,method:string,period:Period,extra:Record<string,string>={}){const params=new URLSearchParams({module:'API',method,format:'JSON',idSite:c.matomoSiteId,period:'range',date:`${period.start},${period.end}`,filter_limit:String(c.analyticsCap),token_auth:c.matomoTokenAuth,...extra});const response=await fetch(matomoEndpoint(c.matomoUrl),{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:params,signal:AbortSignal.timeout(15000)});if(!response.ok)throw Error(`Matomo Reporting API returned HTTP ${response.status}.`);const body=await response.json() as unknown;if(body&&typeof body==='object'&&'result'in body&&(body as {result?:unknown}).result==='error')throw Error(`Matomo Reporting API error: ${String((body as {message?:unknown}).message||'unknown error')}`);return body}

export class MatomoProvider implements AnalyticsProvider{name='matomo' as const;constructor(private c:Config){}capabilities(){return['page URL report','site-level referrer context','Matomo visits and pageviews']}async landingEvidence(period:Period){const [pageResponse,referrerResponse]=await Promise.all([matomoRequest(this.c,'Actions.getPageUrls',period,{flat:'1'}),matomoRequest(this.c,'Referrers.getReferrerType',period)]);const pageRows=Array.isArray(pageResponse)?pageResponse:[],referrerRows=Array.isArray(referrerResponse)?referrerResponse:[];const rows=pageRows.map(row=>{const r=row as Record<string,unknown>;return{url:String(r.label||''),acquisition:null,metrics:{visits:number(r.nb_visits),pageviews:number(r.nb_hits),uniquePageviews:number(r.nb_uniq_pageviews),entries:number(r.entry_nb_visits),bounceRate:number(r.bounce_rate)}}}).filter(row=>row.url);const sourceSummaries=referrerRows.map(row=>{const r=row as Record<string,unknown>;return{type:'Matomo referrer type',value:String(r.label||'(not set)'),metrics:{visits:number(r.nb_visits),actions:number(r.nb_actions),conversions:number(r.nb_conversions)}}});const capped=pageRows.length>=this.c.analyticsCap;return{provider:this.name,metricLabels:matomoLabels,rows,sourceSummaries,coverage:{complete:!capped,limitations:[...(capped?[`Matomo page URL response reached the configured ${this.c.analyticsCap}-row cap.`]:[]),'Matomo referrer context is site-level in this evidence; it is not attributed to individual page rows.']}}}}

export class NoneProvider implements AnalyticsProvider{name='none' as const;capabilities(){return[]}async landingEvidence(_period:Period){return{provider:this.name,metricLabels:{},rows:[],sourceSummaries:[],coverage:{complete:true,limitations:['No analytics provider is configured. GSC-only evidence is available.']}}}}

export async function configuredOutcomeEvents(c:Config,period:Period){if(c.analyticsProvider!=='ga4')return{available:false,reason:'Configured outcome events are currently supported for GA4 only.',events:[]};if(!c.outcomeEvents.length)return{available:false,reason:'GA4_OUTCOME_EVENT_NAMES is not configured.',events:[]};const api=google.analyticsdata({version:'v1beta',auth:oauth(c).client}),r=await api.properties.runReport({property:`properties/${c.ga4PropertyId}`,requestBody:{dateRanges:[{startDate:period.start,endDate:period.end}],dimensions:[{name:'eventName'}],metrics:[{name:'eventCount'}],dimensionFilter:{filter:{fieldName:'eventName',inListFilter:{values:c.outcomeEvents}}}}});return{available:true,events:(r.data.rows||[]).map(x=>({name:x.dimensionValues?.[0]?.value||'',count:Number(x.metricValues?.[0]?.value||0)})),limitation:'Event counts are property-level for the selected period; they are not attributed to GSC queries.'}}

export function analyticsProvider(c=config()):AnalyticsProvider{if(c.analyticsProvider==='ga4'){if(!c.ga4PropertyId)throw Error('GA4_PROPERTY_ID is required when ANALYTICS_PROVIDER=ga4.');return new Ga4Provider(c)}if(c.analyticsProvider==='matomo'){if(!c.matomoUrl||!c.matomoSiteId||!c.matomoTokenAuth)throw Error('MATOMO_URL, MATOMO_SITE_ID, and MATOMO_TOKEN_AUTH are required when ANALYTICS_PROVIDER=matomo.');return new MatomoProvider(c)}return new NoneProvider()}
