import fs from 'node:fs';
import path from 'node:path';
import {config,normalize} from './core.js';

const sourceExtensions=/\.(md|mdx|astro|html)$/i;
const ignoredDirectories=new Set(['node_modules','.git','dist']);
const files=(directory:string,output:string[]=[]):string[]=>{for(const entry of fs.readdirSync(directory,{withFileTypes:true})){if(ignoredDirectories.has(entry.name))continue;const full=path.join(directory,entry.name);if(entry.isDirectory())files(full,output);else if(sourceExtensions.test(entry.name))output.push(full)}return output};
const slugFor=(url:string,c:any)=>normalize(url,c).replace(/^\/+|\/+$/g,'').split('/').pop()||'';
const titleFor=(text:string)=>/^title:\s*["']?(.+?)["']?\s*$/m.exec(text)?.[1]||null;
const stopWords=new Set(['about','after','also','and','are','can','content','does','for','from','have','how','into','more','that','the','this','what','when','where','which','with','your']);
const searchableTerms=(terms:string[])=>[...new Set(terms.flatMap(term=>term.toLocaleLowerCase().match(/[\p{L}\p{N}][\p{L}\p{N}-]{3,}/gu)||[]).filter(term=>!stopWords.has(term)))].slice(0,20);

export function contentEvidence(text:string,terms:string[]){const wanted=searchableTerms(terms),body=text.replace(/^---\s*\r?\n[\s\S]*?\r?\n---\s*\r?\n?/,'').trim(),lines=body.split(/\r?\n/),headings=lines.flatMap(line=>{const match=/^(#{1,6})\s+(.+?)\s*$/.exec(line);if(!match)return[];const matchedTerms=wanted.filter(term=>match[2].toLocaleLowerCase().includes(term));return matchedTerms.length?[{level:match[1].length,heading:match[2],matchedTerms}]:[]}),excerpts=body.split(/\n\s*\n/).map(part=>part.replace(/\s+/g,' ').trim()).filter(part=>part&&!/^#{1,6}\s/.test(part)).flatMap(part=>{const matchedTerms=wanted.filter(term=>part.toLocaleLowerCase().includes(term));return matchedTerms.length?[{text:part.slice(0,500),matchedTerms}]:[]}).slice(0,5);return{title:titleFor(text),matchingHeadings:headings.slice(0,10),excerpts}}

function mappedFiles(url:string,c:any){if(!c.repositoryPath||!fs.existsSync(c.repositoryPath))return[];const key=normalize(url,c),slug=slugFor(url,c);return files(c.repositoryPath).flatMap(file=>{const text=fs.readFileSync(file,'utf8'),base=path.basename(file).replace(sourceExtensions,'');if(text.includes(key)||text.includes(url))return[{file,text,mapping:'direct_url_reference'}];if(base===slug)return[{file,text,mapping:'filename_slug'}];return[]}).slice(0,20)}

export async function repositoryContext(url:string){const c=config(),key=normalize(url,c);if(!c.repositoryPath)return{configured:false,reason:'SITE_SIGNAL_REPOSITORY_PATH is not configured.'};if(!fs.existsSync(c.repositoryPath))return{configured:false,reason:'Configured repository path does not exist.'};const sourceFiles=mappedFiles(url,c).map(({file,mapping})=>({file,mapping}));return{configured:true,targetPath:key,sourceFiles,limitation:'Only configured local source files are inspected. URL mapping is either a direct URL reference or an exact filename-slug match; an empty result is valid.'}}

export async function pageSourceContext(url:string,terms:string[]=[]){const c=config(),key=normalize(url,c);if(!c.repositoryPath)return{configured:false,reason:'SITE_SIGNAL_REPOSITORY_PATH is not configured.'};if(!fs.existsSync(c.repositoryPath))return{configured:false,reason:'Configured repository path does not exist.'};const sources=mappedFiles(url,c).map(({file,text,mapping})=>({file,mapping,...contentEvidence(text,terms)}));return{configured:true,targetPath:key,terms:searchableTerms(terms),sources,limitation:'Source context is bounded excerpts and headings from explicitly configured local files. It shows matching text, not whether the page answers the question well.'}}

export async function internalLinkContext(url:string,terms:string[]=[]){const c=config(),repo=await repositoryContext(url),key=normalize(url,c);let sitemap:any={configured:false};if(c.sitemapUrl){try{const text=await(await fetch(c.sitemapUrl)).text();sitemap={configured:true,containsTarget:text.includes(url)||text.includes(key)}}catch{sitemap={configured:true,error:'Could not fetch configured sitemap.'}}}const verifiedOpportunities=c.repositoryPath&&fs.existsSync(c.repositoryPath)?files(c.repositoryPath).flatMap(file=>{const text=fs.readFileSync(file,'utf8'),matchedTerms=terms.filter(term=>term.length>3&&text.toLowerCase().includes(term.toLowerCase()));return matchedTerms.length&&!text.includes(key)&&!text.includes(url)?[{file,matchedTerms}]:[]}).slice(0,20):[];return{target:url,repository:repo,sitemap,verifiedOpportunities,limitation:'Candidates are verified local files that contain selected query text and do not already link to the target. Review editorial relevance and anchor context in the chat client.'}}
